### ISSUE TITLE
bug: demo env creation hangs at "Wating for nginx ingress with SSL passthrough to be ready..."

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#2725]
### Describe the bug

A user trying the demo env creation script reported that it hung.

### Output from KubeStellar-Snapshot.sh

Not available.

### Steps To Reproduce

No more is known.

### Expected Behavior

no failure

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment]
This has been reported to happen after the merge of #2719

**Comment by pratik-mahalle** [comment]
Hey @MikeSpreitzer Can you please tell what is step to reproduce this issue?

**Comment by antedotee** [comment]
I tried to reproduce the hanging issue, but was unable to do so, but I realized that it would be a good idea to set a timeout if it ever happened and keeps logging when it is stuck on the line "Waiting for nginx ingress with SSL passthrough to be ready..." which can provide much better visibility during the process. I would like to hear your take regarding this.
I am attaching screenshot of the output of the improved script I implemented:

<img width="1536" height="1534" alt="Image" src="https://github.com/user-attachments/assets/b4ba5b41-45da-46d2-8a2f-4f8870657fcb" />

**Comment by MikeSpreitzer** [comment]
I do not know how to reproduce the original user's problem.

**Comment by clubanderson** [comment]
are we making progress on this @rishi-jat ?

**Comment by rishi-jat** [comment]
@clubanderson, yes just waiting for @MikeSpreitzer’s review on the PR. I’ll proceed further as soon as I receive feedback.

**Comment by MikeSpreitzer** [comment]
@clubanderson, @rishi-jat: I doubt that we still have a problem in this regard. Nobody has reported the same symptom in a long time.

**Comment by rishi-jat** [comment]
@MikeSpreitzer I feel the same I haven’t seen this flake recently either. So rather than continuing to chase the issue itself, I think this PR is still useful as an enhancement: it improves diagnostics, uses infinite timeout, and adds more robust ingress wait logic for k3d.

**Comment by clubanderson** [comment]
Issues go stale after 90d of inactivity.
After a furter 30 days, they will turn rotten.
Mark the issue as fresh with `/remove-lifecycle stale`.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

**Comment by clubanderson** [comment]
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

**Comment by clubanderson** [comment]
Rotten issues close after 30d of inactivity.
Reopen the issue with `/reopen`.
Mark the issue as fresh with `/remove-lifecycle rotten`.

/close
